name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Backend-API/**'    # Updated path
      - 'package.json'          # Added
      - 'Dockerfile'            # Added
      - '.github/workflows/deploy-docker.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .                # This is correct as Dockerfile is in root
        file: ./Dockerfile        # This is correct
        push: true
        tags: masharma2004/labbooker-backend:latest